# Generated by Django 4.2.13 on 2024-07-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_message_remove_mailingsettings_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки'),
        ),
    ]
