# Generated by Django 4.2.13 on 2024-07-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_alter_mailingsettings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('change_status', 'Can change status')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройка рассылок'},
        ),
    ]
