# Generated by Django 4.2.13 on 2024-08-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0008_mailingsettings_time_last_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='comments',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Комментарии'),
        ),
    ]
